import { Suspense } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Check, Clock3, Coffee, Star, Wifi } from "lucide-react";
import ApartmentsSection, { ApartmentsSkeleton } from "@/components/ApartmentsSection";
import AvailabilityWidget from "@/components/AvailabilityWidget";
import PhotoLightbox from "@/components/PhotoLightbox";
import SiteFooter from "@/components/SiteFooter";
import SiteNav from "@/components/SiteNav";

export default function PublicHome() {
  return <div className="site min-h-screen overflow-hidden bg-[#f8f6f1] text-[#202b28]">
    <section className="site-hero relative min-h-[710px] bg-[#263b34] text-[#f7f4ed]"><Image src="/images/houzzhills-hero.png" alt="Warm Houzzhills serviced apartment interior" fill sizes="100vw" preload className="absolute inset-0 h-full w-full object-cover opacity-60" /><div className="absolute inset-0 bg-gradient-to-r from-[#142b25]/95 via-[#19372f]/85 to-[#1c3930]/55" /><div className="absolute right-[-8%] top-[-12%] h-[640px] w-[58%] rounded-[45%] border border-white/10 rotate-[-16deg]" />
      <SiteNav />
      <div className="relative z-10 mx-auto grid w-full min-w-0 max-w-7xl items-center gap-12 px-6 pb-20 pt-20 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:pb-28 lg:pt-24"><div className="w-full min-w-0 max-w-xl"><p className="mb-6 flex items-center gap-3 text-[10px] font-semibold uppercase tracking-[.28em] text-[#e0b876]"><span className="h-px w-8 bg-[#e0b876]" /> Stay a little differently</p><h1 className="font-serif text-[clamp(2.75rem,12vw,5.375rem)] leading-[.96] tracking-[-.04em] sm:text-7xl lg:text-[86px]">Your place<br /><i className="font-normal text-[#ddb276]">in Kaduna.</i></h1><p className="mt-8 max-w-md text-base leading-7 text-[#cad5cf]">Thoughtful serviced apartments for long weekends, longer stays, and everything in between. Come in, settle down, stay awhile.</p><div className="mt-9 flex w-full min-w-0 flex-wrap items-center gap-4"><Link href="#apartments" className="group flex items-center gap-3 rounded-full bg-[#dfb56f] px-6 py-3.5 text-sm font-semibold text-[#263b34] hover:bg-[#edc98e]">Find your apartment <span className="grid h-6 w-6 place-items-center rounded-full bg-[#263b34] text-[#dfb56f]"><ArrowUpRight size={14} /></span></Link><a href="#apartments" className="flex items-center gap-2 text-sm text-[#d6dfd9] hover:text-white">Explore the spaces <ArrowUpRight size={15} /></a></div></div><div className="relative hidden min-h-[390px] lg:block"><div className="absolute inset-7"><PhotoLightbox src="/images/one-bedroom-card.png" alt="Houzzhills one bedroom apartment living room" className="h-full w-full rounded-[38%_62%_54%_46%/44%_40%_60%_56%] shadow-2xl shadow-black/25" imageClassName="object-cover" sizes="(min-width: 1024px) 48vw, 100vw" /></div><div className="pointer-events-none absolute inset-0 rounded-[38%_62%_54%_46%/44%_40%_60%_56%] border border-white/15 rotate-6" /><div className="absolute bottom-3 left-0 rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur-md"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#dfb56f] text-[#263b34]"><Star size={15} fill="currentColor" /></div><div><b className="block text-sm">4.9 / 5 guest rating</b><span className="text-xs text-[#cbd7d0]">A quiet favourite in Kaduna</span></div></div></div><div className="absolute right-2 top-12 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs text-[#dce5df] backdrop-blur-md">Kaduna · Nigeria</div></div></div>
      <div id="availability" className="relative z-10 mx-auto w-full min-w-0 max-w-7xl px-4 sm:px-6 lg:px-10"><AvailabilityWidget /></div>
    </section>
    <section className="site-reveal mx-auto max-w-7xl scroll-mt-6 px-6 py-20 lg:px-10 lg:py-28" id="apartments"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#b28247]">Choose your pace</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-tight tracking-tight text-[#263b34] sm:text-5xl">Spaces that make staying feel easy.</h2></div><p className="max-w-xs text-sm leading-6 text-stone-500">Every apartment is designed as a calm base for Kaduna: warm, practical, and ready for real life.</p></div><Suspense fallback={<ApartmentsSkeleton />}><ApartmentsSection /></Suspense><div className="mt-10 text-center"><Link href="#availability" className="inline-flex items-center gap-2 text-sm font-semibold text-[#31715d] hover:text-[#1f4d3f]">See availability <ArrowUpRight size={15} /></Link></div></section>
    <section className="site-reveal mx-auto max-w-7xl px-6 pb-20 lg:px-10 lg:pb-28" id="gallery"><div className="mb-10 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#b28247]">A closer look</p><h2 className="mt-4 font-serif text-4xl text-[#263b34] sm:text-5xl">See yourself here.</h2></div><span className="hidden text-xs text-stone-500 sm:block">Designed for slow mornings and easy evenings.</span></div><div className="grid gap-4 sm:grid-cols-[1.35fr_.65fr]"><PhotoLightbox src="/images/houzzhills-hero.png" alt="Houzzhills apartment living room" className="h-[280px] w-full rounded-[28px] bg-[#c9a982] sm:h-[420px]" sizes="(max-width: 640px) 100vw, 68vw"><span className="pointer-events-none absolute bottom-5 left-5 text-sm font-medium text-white">Living spaces with room to breathe</span></PhotoLightbox><PhotoLightbox src="/images/houzzhills-bedroom.png" alt="Houzzhills apartment bedroom" className="h-[280px] w-full rounded-[28px] bg-[#b8c5c1] sm:h-[420px]" sizes="(max-width: 640px) 100vw, 32vw"><span className="pointer-events-none absolute bottom-5 left-5 text-sm font-medium text-white">Rest, properly</span></PhotoLightbox></div></section>
    <section className="site-reveal border-y border-[#e6dfd2] bg-[#efeadf]" id="experience"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[1fr_1.1fr] lg:items-center lg:px-10 lg:py-28"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#b28247]">The Houzzhills standard</p><h2 className="mt-4 max-w-lg font-serif text-4xl leading-tight tracking-tight text-[#263b34] sm:text-5xl">The details are quiet. The difference is not.</h2><p className="mt-6 max-w-md text-sm leading-7 text-stone-600">From the first message to the last morning coffee, we make the practical parts feel considered. You get the freedom of an apartment with the reassurance of a team close by.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white/60 p-4"><Wifi className="text-[#31715d]" size={18} /><b className="mt-3 block text-sm">Fast, reliable Wi-Fi</b><span className="mt-1 block text-xs text-stone-500">Work, stream, stay connected.</span></div><div className="rounded-2xl bg-white/60 p-4"><Clock3 className="text-[#31715d]" size={18} /><b className="mt-3 block text-sm">A team on hand</b><span className="mt-1 block text-xs text-stone-500">Support when you need it.</span></div><div className="rounded-2xl bg-white/60 p-4"><Coffee className="text-[#31715d]" size={18} /><b className="mt-3 block text-sm">Your own rhythm</b><span className="mt-1 block text-xs text-stone-500">Kitchen, space, no rush.</span></div><div className="rounded-2xl bg-white/60 p-4"><Check className="text-[#31715d]" size={18} /><b className="mt-3 block text-sm">Simple direct booking</b><span className="mt-1 block text-xs text-stone-500">Clear rates, secure payment.</span></div></div></div><div className="relative min-h-[390px] overflow-hidden rounded-[30px] bg-gradient-to-br from-[#c9a982] via-[#96795b] to-[#3b4c43]"><div className="absolute inset-0 opacity-50 [background:radial-gradient(circle_at_30%_30%,#f3dfbd66,transparent_28%),linear-gradient(120deg,transparent_35%,#172e274d)]" /><div className="absolute bottom-6 left-6 max-w-[230px] rounded-2xl border border-white/20 bg-[#1e352d]/70 p-5 text-white backdrop-blur-md"><Star className="text-[#e1b66f]" size={17} fill="currentColor" /><p className="mt-4 font-serif text-xl leading-tight">“It felt like our own apartment, only better looked after.”</p><span className="mt-4 block text-xs text-white/60">— Amina, Kaduna</span></div></div></div></section>
    <section className="site-reveal mx-auto max-w-7xl px-6 py-20 text-center lg:px-10 lg:py-28" id="location"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#b28247]">Make Kaduna yours</p><h2 className="mx-auto mt-4 max-w-2xl font-serif text-5xl leading-tight tracking-tight text-[#263b34]">Stay for the moment.<br /><i className="font-normal text-[#b28247]">Make it yours.</i></h2><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-stone-500">Close to the places that bring Kaduna to life. Book directly for our best available rate.</p><Link href="#availability" className="site-cta mt-8 inline-flex items-center gap-3 rounded-full bg-[#263b34] px-7 py-4 text-sm font-semibold text-white hover:bg-[#1a2c26]">Book your stay <ArrowUpRight size={16} /></Link></section>
    <SiteFooter />
  </div>;
}
